accountapp/urls.py
from django.urls import path
from . import views
from accountapp.views import myblog,login_view,logout_view

app_name = "accountapp"

urlpatterns = [
    path('',myblog, name='myblog'),
    path("login",views.login_view, name='login'),
    path('logout',views.logout_view, name='logout'),
    path("signup",views.signup, name='signup'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('accountapp.urls')),
    path('', include('board.urls'))
]

board/urls.py
from django.urls import path
from . import views
from board.views import board_list, gallery

app_name = "board"

urlpatterns = [
    path("board",views.board_list, name='board'),
    path('gallery',views.gallery, name='gallery'),
]

AES/models.py
# Create your models here.
from django.db import models

class EncryptedData(models.Model):
    encrypted_data = models.TextField()

accountapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    student_id = models.CharField(max_length=10)
    email = models.EmailField()
    password = models.CharField(max_length=100)


class board(models.Model):
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=50)

board/models.py
from django.db import models

# Create your models here.

AES/views.py
from django.shortcuts import render, redirect
from .encryption_module import SymmetricEncryption
from .models import EncryptedData

def encrypt_data(request):
    client_password = "password"
    encryption_module = SymmetricEncryption(client_password.encode())
    
    original_data = "Sensitive information."
    encrypted_data = encryption_module.encrypt(original_data)
    
    EncryptedData.objects.create(encrypted_data=encrypted_data)
    
    return redirect('admin_page')

accountapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from .models import User

# Create your views here.

def myblog(request):
    return render(request, 'base.html')

def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            print("로그인 성공")
            login(request, user)
            return redirect('accountapp:myblog')
        else:
            print("로그인 실패")
    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('accountapp:myblog')


def signup(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        user = User.objects.create_user(username, email, password)
        user.save()
        return redirect('accountapp:login')

    return render(request, 'signup.html')


board/views.py
from django.shortcuts import render

# Create your views here.

def board_list(request):
    return render(request, 'board.html')

def gallery(request):
    return render(request, 'gallery.html')

accountapp/templates/login.html
로그인 페이지

<form action="" method="POST">
    {% csrf_token %}
    <input name="username", type="text">
    <input name="password", type="password">
    <input type="submit", value="로그인">
</form>
<a href="{% url 'accountapp:signup' %}">회원가입</a>



accountapp/templates/signup.html
회원가입 페이지

<form action="" method="POST">
    {% csrf_token %}
    <p>아이디</p>
    <input name="username", type="text">
    <p>비밀번호</p>
    <input name="password", type="password">
    <p>이메일</p>
    <input name="email", type="text">
    <input type="submit", value="회원가입">
</form>

<a href="{% url 'accountapp:login' %}">돌아가기</a>

board/templates/board.html
<a href="{% url 'board:gallery' %}">글 작성하기</a>
<div class = 'contanier'>
    <div class = "row pt-4 my-3">
        <div class = "col-md-12">
            <h3>게시판</h3>
        </div>
    </div>
    <div class="row my-3">
        <table class = "table table-hover table-bordered">
            <thead>
                <th>NO</th>
                <th>작성자</th>
                <th>제목</th>
                <th>내용</th>
            </thead>
            <tbody>
                {% for post in board_list %}
                    <tr>
                        <td>{{ forloop.revcounter }}</td>
                        <td>{{ post.username}}</td>
                        <td><a href="{% url 'board:detail' %}">{{ post.title }}</a></td>
                        <td>{{ post.content|truncatechars:5 }}</td>
                        <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>
    </div>
</div>

board/templates/detail.html

<table>
    <tr>
        <td>글 제목 : {{ board_list.title }}</td>
    </tr>
    <tr>
        <td>
            <p>글 내용</p>
            <p>{{ board_list.content|linebreaks }}</p>
        </td>
    </tr>
</table>

board/templates/gallery.html
{% block content %}
<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            <h3>글 쓰기</h3>
        </div>
    </div>
    <div class="row my-3"></div>
        <form action="", method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="padding: 5px 50px; float:right";>
                <input type="submit" value="글 등록">
            </div>
        </form>
    </div>

{% endblock %}

templates/base.html
블로그 페이지


<nav>
    {% if user.is_authenticated %}
        <a href="{% url 'accountapp:logout' %}">로그아웃</a>
        <a href="{% url 'board:board' %}">게시판</a>
    {% else %}
        <a href="{% url 'accountapp:login' %}">로그인</a>
    {% endif %}
</nav>